name: vakinha_burger_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  args: ^2.3.1
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  dio: ^4.0.6
  dio_http2_adapter: ^2.0.0
  dotenv: ^3.0.0
  mysql1: ^0.20.0
  shelf_static: ^1.1.1

dev_dependencies:
  http: ^0.13.5
  lints: ^2.0.1
  test: ^1.22.2
  build_runner: ^2.3.3
  shelf_router_generator: ^1.0.5
  